exclude :test_initialize_failure, "bind error message does not include address details"
exclude :test_initialize_resolv_timeout_with_connection_failure, "hangs: IO.select does not detect failed nonblocking connect to closed port"
exclude :test_initialize_with_hostname_resolution_failure_after_connection_failure, "hangs: IO.select does not detect failed nonblocking connect to closed port"
exclude :test_inspect, "Expected /AF_INET/ to match \"#<TCPServer:fd 38>\"."
exclude :test_recvfrom, "SocketError: need IPv4 or IPv6 address"
