exclude :test_bind, "Expected /bind\\(2\\)\\ for\\ 127\\.0\\.0\\.1:50393/ to match \"Address already in use - bind(2)\"."
exclude :test_closed_read, "retain-on-retag; test timed out"
exclude :test_getnameinfo, "Socket::ResolutionError not raised for AF_UNIX getnameinfo"
exclude :test_socket_new_cloexec, "Failed assertion, no message given."
exclude :test_tcp_socket_hostname_resolution_failed_after_connection_failure, "hangs: IO.select does not detect failed nonblocking connect to closed port"
exclude :test_tcp_socket_resolv_timeout_with_connection_failure, "hangs: IO.select does not detect failed nonblocking connect to closed port"
exclude :test_tcp_cloexec, "Failed assertion, no message given."
exclude :test_timestamp, "NoMethodError: undefined method 'cmsg_is?' for nil"
exclude :test_udp_server, "spurious; failed in CI with `RuntimeError: thread killed`"
exclude :test_unix, "Failed assertion, no message given."
